### ISSUE TITLE
When setting it as a global Home Assistant theme, Mushroom Climate Card not is themed properly.

### ISSUE THREAD

**Issue by MJHeijster** [veniplex/hass-idx-theme#1]
**Describe the bug**
Go to the user settings (bottom left, click your name/photo), set the theme:
![image](https://github.com/user-attachments/assets/04e7f278-93f6-4155-97ae-df13cbd40104)

The mushroom look goes from (theme set to default):
![image](https://github.com/user-attachments/assets/76ee7fa0-49ca-4f23-a1bc-6139025ef29a)
To (theme set to IDX):
![image](https://github.com/user-attachments/assets/8cabc130-b4c8-4af2-9114-645389742fca)

This applies to both mobile and with browsers.

YAML:
type: custom:mushroom-climate-card
entity: climate.smart_ac_control_wr0091173632
name: AC
hvac_modes:
  - cool
  - "off"
  - heat
show_temperature_control: true
collapsible_controls: false
fill_container: false
layout_options:
  grid_columns: 4
  grid_rows: 2

Other than that, I love this theme :)

**Comment by veniplex** [comment]
Hi @MJHeijster. Thank you for bringing this up. I will work on a fix later today. I know, Mushroom does support custom theming - so this should be relativley easy to solve :).

**Comment by veniplex** [comment]
Okay... so it took me a while to figure out the problem.

The "button" that is deactivated / inactive gets its background color from:
```css
button {
  background-color: var(--bg-color);
  ...
}
```

`bg-color` is defined inside a `#shadow-root`:
```css
:host {
  bg-color: rgba(var(--rgb-primary-text-color), 0.05);
  ...
}
```

This means it inherits the color from `--rgb-primary-text-color`, which can be defined by a custom theme like IDX. However, when I try to set a color for `--rgb-primary-text-color`, e.g. `rgb-primary-text-color: rgb(255, 0, 0)` (red), nothing really changes. This is because `bg-color` has a hard-coded opacity of `0.05`. I found no way to change this opacity yet. Also, a defined `bg-color` variable inside a custom theme, like IDX, is overwritten by the `bg-color` inside the `#shadow-root`, like mentioned above.

In conclusion there are thre options basically:
1. Change the background color of the whole card to a much lighter color. This will have an effect on EVERY card and it destroys basically the whole theme... so this does not work.
2. Change the color of `rgb-primary-text-color:` to the brightest color possible, which is white.
3. Change the value of `rgb-primary-text-color:` to a two number value, like `255, 255`, so that the `rgba()` value of `bg-color` gets tricked to use `0.05` as the value for blue (RGB). With this approach it is not possible to get a color that fits the theme... (at least I don't know how :D).

So, for now I defined `rgb-primary-text-color: 255, 255, 255` inside the `dark:` mode section. This makes the button at least a bit lighter. But as long as I don't have the option to change the opacity, I cannot really change much more :(...

**Before:** (`rgb-primary-text-color: 51, 51, 51`)
![image](https://github.com/user-attachments/assets/50636c49-995b-4b01-ab50-82c58622a2d7)

**After:** (`rgb-primary-text-color: 255, 255, 255`)
![image](https://github.com/user-attachments/assets/bd9de217-ee33-435b-97fc-d6e624e421b6)

**Comment by MJHeijster** [comment]
I'm glad I don't have to looks at design things like this in my line of work too much...

The colors are really close (#1B1F25 vs #1C2129), so looks good so far. Maybe I should phase out mushroom on my end and not have this problem :D
